version: '3'
networks:
  web:
    external: true
  internal:
    external: false

services:
  vms:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/vms
    ports:
      - 8000:80
  